create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  cpf text not null unique,
  cep text not null,
  street text not null,
  neighborhood text not null,
  number text not null,
  complement text not null default '',
  password_hash text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  price numeric(10, 2) not null check (price >= 0),
  description text not null default '',
  image text,
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  delivery text not null check (delivery in ('pickup', 'shipping')),
  total numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id),
  product_id text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null
);

create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null
);

alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.sessions enable row level security;

insert into public.products (id, name, category, price, description, image, stock) values
('box-mega-luar-clefable', 'Box Mega Luar Clefable', 'pokemon-tcg', 125, 'Caixa fechada, 8 pacotes.', 'assets/produtos/box-clefable.jpg', 1),
('colecao-arco-iris-evolucoes-prismaticas', 'Coleção Arco-Íris Evoluções Prismáticas', 'pokemon-tcg', 210, 'Caixa fechada, 10 pacotes.', 'assets/produtos/box-eevee.jpg', 1),
('blister-triplo-escuridao-absoluta', 'Blister Triplo Escuridão Absoluta', 'pokemon-tcg', 42.50, '3 pacotes.', 'assets/produtos/triple-escuridão.jpg', 2),
('blister-triplo-caos-ascendente', 'Blister Triplo Caos Ascendente', 'pokemon-tcg', 42.50, '3 pacotes.', 'assets/produtos/triple-caos.jpg', 2),
('blister-unitario-equilibrio-perfeito', 'Blister Unitário Equilíbrio Perfeito', 'pokemon-tcg', 13, 'Booster unico', 'assets/produtos/buniequperf.jpg', 2),
('blister-unitario-escuridao-absoluta', 'Blister Unitário Escuridão Absoluta', 'pokemon-tcg', 13, 'Booster unico', 'assets/produtos/bunicoescabs.jpg', 1),
('bleach-remix-vol-2', 'Bleach Remix Vol. 2', 'mangas', 45, 'Usado.', 'assets/produtos/bleach2.jpg', 1),
('bleach-remix-vol-3', 'Bleach Remix Vol. 3', 'mangas', 45, 'Usado.', 'assets/produtos/bleach3.jpg', 1),
('bleach-remix-vol-4', 'Bleach Remix Vol. 4', 'mangas', 45, 'Usado.', 'assets/produtos/bleach4.jpg', 1),
('bleach-remix-vol-5', 'Bleach Remix Vol. 5', 'mangas', 45, 'Usado.', 'assets/produtos/bleach5.jpg', 1),
('radiant-vol-14', 'Radiant Vol. 14', 'mangas', 27, 'Usado.', 'assets/produtos/radiand14.jpg', 1),
('vagabond-vol-1', 'Vagabond Vol. 1', 'mangas', 36.50, 'Novo.', 'assets/produtos/vagabond1.jpg', 1),
('gantz-vol-3', 'Gantz Vol. 3', 'mangas', 27, 'Novo.', 'assets/produtos/gantz3.jpg', 1),
('gantz-vol-4', 'Gantz Vol. 4', 'mangas', 27, 'Novo.', 'assets/produtos/gantz4.jpg', 1),
('noragami-vol-23', 'Noragami Vol. 23', 'mangas', 22.99, 'Usado.', 'assets/produtos/noragami23.jpg', 1),
('sleeves-central-100un', 'Sleeves Central (100un)', 'acessorios', 23, 'Tamanho padrão para cartas TCG.', 'assets/produtos/sleevecentral.jpg', 16)
on conflict (id) do nothing;

create or replace function public.create_store_order(p_user_id bigint, p_delivery text, p_items jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id bigint;
  item jsonb;
  product_row public.products%rowtype;
  quantity integer;
  order_total numeric(10, 2) := 0;
begin
  if p_delivery not in ('pickup', 'shipping') then
    raise exception 'Forma de recebimento inválida';
  end if;

  for item in select * from jsonb_array_elements(p_items) loop
    quantity := (item->>'quantity')::integer;
    select * into product_row from public.products where id = item->>'id' and active = true for update;
    if not found or quantity < 1 or quantity > product_row.stock then
      raise exception 'Produto sem estoque ou quantidade inválida';
    end if;
    order_total := order_total + product_row.price * quantity;
  end loop;

  insert into public.orders (user_id, delivery, total) values (p_user_id, p_delivery, order_total) returning id into new_order_id;

  for item in select * from jsonb_array_elements(p_items) loop
    quantity := (item->>'quantity')::integer;
    select * into product_row from public.products where id = item->>'id' for update;
    insert into public.order_items (order_id, product_id, product_name, quantity, unit_price)
      values (new_order_id, product_row.id, product_row.name, quantity, product_row.price);
    update public.products set stock = stock - quantity where id = product_row.id;
  end loop;
  return new_order_id;
end;
$$;
